import type { Theme } from "@/components/ui/theme-provider";

export const shadesofpurpleTheme: Theme = {
  border: {
    color: "#b362ff",
    focusColor: "#c792ff",
    style: "round",
  },
  colors: {
    accent: "#ff7ac6",
    accentForeground: "#1a102b",
    background: "#1a102b",
    border: "#b362ff",
    error: "#ff7ac6",
    errorForeground: "#1a102b",
    focusRing: "#c792ff",
    foreground: "#f5f0ff",
    info: "#7dd4ff",
    infoForeground: "#1a102b",
    muted: "#100918",
    mutedForeground: "#b362ff",
    primary: "#c792ff",
    primaryForeground: "#1a102b",
    secondary: "#2a2035",
    secondaryForeground: "#f5f0ff",
    selection: "#c792ff",
    selectionForeground: "#1a102b",
    success: "#7be0b0",
    successForeground: "#1a102b",
    warning: "#ffd580",
    warningForeground: "#1a102b",
  },
  // Shades of Purple — deep purple bg with vivid hot pink, cyan, yellow,
  // mint accents. The hot pink + electric violet are this theme's identity,
  // so we lean into the 280-340° band our default avoids.
  creaturePalette: {
    hues: [325, 340, 0, 50, 110, 175, 205, 260, 290],
    saturation: 0.85,
    lightness: 0.68,
    lightnessJitter: 0.05,
  },
  name: "shadesofpurple",
  spacing: {
    0: 0,
    1: 1,
    2: 2,
    3: 3,
    4: 4,
    6: 6,
    8: 8,
  },
  typography: {
    base: "",
    bold: true,
    lg: "bold",
    sm: "dim",
    xl: "bold",
  },
};
